---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:

  children:

    # Role specific breakout

    sensor-common:
      children:
        sensors:

    bro:
      children:
        sensors:

    docker:
      children:
        sensors:
        servers:

    kibana:
      children:
        servers:

    portainer:
      children:
        master-servers:

    #haproxy:
    #  children:
    #    master-servers:

    elasticsearch:
      children:
        servers:

    logstash:
      children:
        servers:

    suricata:
      children:
        sensors:

    filebeat:
      children:
        sensors:

    zookeeper:
      children:
        sensors:

    kafka:
      children:
        sensors:

    harbor:
      children:
        master-servers:

    stenographer:
      children:
        sensors:

    # Broad categories for convienience
    sensors:

      hosts:
        rocksensor1.lan:
          ansible_hostname: rocksensor1.lan
          ansible_user: root
          ansible_connection: ssh

    servers:

      children:

        master-servers:
          hosts:
            rockserver1.lan:
              ansible_hostname: rockserver1.lan
              ansible_user: root
              ansible_connection: ssh

        ingest:
          # currently nothing here
